---
title: "Cardiac G2P curations"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    theme: lumen
    keep_md: true
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(readxl)
library(openxlsx)
#library(knitr)
library(kableExtra)
library(janitor)
```


<style type="text/css">

h1.title {
  font-size: 50px;
}

</style>

<p style=\"page-break-before: always;\">&nbsp;</p>

```{r convert_xlsx_to_csv, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}

# # read excel supp file
# g2p_formated<-read_excel("CardiacG2P_Additional_File4.xlsx",sheet = 1,col_types = "text") 
# g2p_narative<-read_excel("CardiacG2P_Additional_File4.xlsx",sheet = 2,col_types = "text") %>%
#   select("Narrative"=`Narrative...3`) %>%
#   mutate(across(c("Narrative"), ~ str_replace_all(.,"<br/>","\n")))
# 
# g2p <- g2p_formated %>%
#   cbind(g2p_narative)
# 
# write_csv(g2p,"CardiacG2P_Additional_File4.csv",quote = "all" )

```

```{r read_g2p, message=FALSE, warning=FALSE, include=FALSE}

g2p <- read_csv("CardiacG2P_Additional_File4.csv", col_types = cols(.default = col_character()))


arri_genes <- c("SCN5A","RYR2","CASQ2","CASQ2","CALM1","CALM2","CALM3","TECRL","TRDN","KCNQ1","KCNH2","SCN5A","CALM1","CALM2","CALM3","TRDN","KCNQ1","KCNE1","KCNJ2","CACNA1C","KCNH2","KCNQ1","SLC4A3","KCNJ2","SLC22A5")

chapter1 <- "INHERITED ARRHYTHMIA SYNDROMES"
chapter2 <- "CARDIOMYOPATHY"


```


```{r render_tables, echo=FALSE, results='asis'}

ref_ind <- g2p[1, 3]


cat(paste0("<h2>",chapter1,"</h2>"))
cat(paste0("<h3>",ref_ind,"</h3>"))


for (i in 1:nrow(g2p)){
  

  gene <- g2p[i,] %>% pivot_longer(everything()) %>% janitor::row_to_names(1) %>% tibble() %>% slice_head(n=-1)
  
  if (i==(length(arri_genes)+1)) {
    cat(paste0("<h2>",chapter2,"</h2>"))
  }
  
  
  if ((g2p[i, 3]) != ref_ind) {
    cat(paste0("<h3>",g2p[i, 3],"</h3>"))
    ref_ind <- g2p[i, 3]
  }
      
  # print gene text
  print(
    kbl(gene, 
        full_width = T,
        booktabs = TRUE
        )%>%
    kable_styling(font_size =12,
                  html_font = "sans-serif",
                  bootstrap_options = c("striped", "condensed", "scale_down"))%>% 
      column_spec(1, width = "6cm") %>% 
      row_spec(0, bold = TRUE,font_size =14) %>% 
      row_spec(4, bold = TRUE)
  
  )
  
  #i=1
  narrative <- g2p[i,ncol(g2p)] %>% 
    tibble() %>%  set_names("Narrative") %>% transmute(Narrative = paste0("<br /> \n\n",Narrative))

  # print narrative text
  print(
    kbl(narrative,escape = F,
        full_width = T,
        booktabs = TRUE
        ) %>%
    kable_styling(font_size =12,
                  html_font = "sans-serif",
                bootstrap_options = c("striped", "condensed")) %>% 
      row_spec(0, bold = TRUE,font_size =14)
  
  )
  
  
  cat("\n")
  cat("<br>")
  cat("\n")
  #cat("\\pagebreak")
  cat("<p style=\"page-break-before: always;\">&nbsp;</p>")
  #cat("<p style=\"page-break-after: always;\">&nbsp;</p>")
  
   
}
```

```{r session_info, message=FALSE, warning=FALSE, include=FALSE}

sessionInfo()

```

