name: Deploy MkDocs with Read the Docs theme to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if your default branch is different
      - master
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs and Read the Docs theme
        run: |
          pip install mkdocs-material

      - name: Build MkDocs site
        run: mkdocs build

      - name: Upload MkDocs site
        uses: actions/upload-pages-artifact@v3
        with:
          path: site  # MkDocs outputs files to 'site' by default

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

